### ISSUE TITLE
How may I run iodine on boot?

### ISSUE THREAD

**Issue by ishmumx** [spritsail/iodine#11]
Currently, I run this command on boot and it has been working great:

docker run -p 53:53/udp --cap-add=NET_ADMIN --device /dev/net/tun -e IODINE_HOST=ts.mydomain.co.uk -e IODINE_PASS=mypasswordstringhere spritsail/iodine

I was wondering how I may automate this so it runs on boot. A docker-compose file (yml) with a restart:always property would be great, but I am not sure how. Thank you.

**Comment by frebib** [comment]
Setting a restart policy on the container should have it come up on boot. Docker has some good documentation on these options:
https://docs.docker.com/config/containers/start-containers-automatically/
If you're using docker-compose then these are the options and how to configure them:
https://docs.docker.com/compose/compose-file/compose-file-v3/#restart_policy

Sorry for the severely delayed response
