### ISSUE TITLE
collision with systemd-resolv

### ISSUE THREAD

**Issue by marten-seemann** [spritsail/iodine#4]
I'm trying to run the "bare minimum" setup on a Ubuntu 17.04 server.
I'm getting the following error message:
```
docker: Error response from daemon: driver failed programming external connectivity on endpoint boring_heyrovsky (1ab5b9753ae96b93e8ff2d035ebd60798e015ceba4c3dde0894dff17894fb241): Error starting userland proxy: listen udp 0.0.0.0:53: bind: address already in use.
```

As far as I understand, `netstat -apnu | grep 53` reveals that the reason is that systemd-resolv has already bound to port 53:
```
udp        0      0 127.0.0.53:53           0.0.0.0:*                           1222/systemd-resolv
udp        0      0 0.0.0.0:5355            0.0.0.0:*                           1222/systemd-resolv
udp6       0      0 :::5355                 :::*                                1222/systemd-resolv
```

However, stopping systemd-resolv is not an option, since some other containers need that to communicate with each other. Any idea how to get docker-iodine up and running?

**Comment by frebib** [comment]
You can disable the DNS stub listener that resolved runs if you are not using it https://www.freedesktop.org/software/systemd/man/resolved.conf.html#DNSStubListener=

**Comment by frebib** [comment]
@marten-seemann Did you ever resolve this?

**Comment by frebib** [comment]
Just thinking about it, an alternative would be to bind the iodine container to a different port on the host and then map it back to 53 outside your network assuming that you're using NAT and IPv4

**Comment by marten-seemann** [comment]
@frebib: No, I never managed to get it working.

**Comment by frebib** [comment]
Out of curiosity, what is resolved being used for with Docker?
