### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by nicopace** [spritsail/iodine#8]
```
$ docker run -p 53:53/udp --cap-add=NET_ADMIN --device /dev/net/tun -e IODINE_HOST=$HOST -e IODINE_PASS=$PASS spritsail/iodine
docker: Error response from daemon: driver failed programming external connectivity on endpoint unruffled_ramanujan (3d724581c08703e6285cf2804c2dee974d8b97600d1abf541906b55e6c294bbc): Error starting userland proxy: listen udp 0.0.0.0:53: bind: address already in use.
ERRO[0000] error waiting for container: context canceled 
```

and netstat:
```
$ sudo netstat -tunapl | grep \:53\ 
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      1113/systemd-resolv 
udp    19968      0 127.0.0.53:53           0.0.0.0:*                           1113/systemd-resolv 
```
should not ask for 0.0.0.0:53, but it's own interface 53 port, right?
This is a standard ubuntu 18.04

**Comment by frebib** [comment]
It is conflicting with the systemd-resolve local resolver. See my comment here: https://github.com/spritsail/iodine/issues/4#issuecomment-313345629

Let me know how you get on

**Comment by frebib** [comment]
I feel like there should be a clause about this in the readme. This repository definitely needs some work

**Comment by nicopace** [comment]
did that and ended up without dns resolution at a system level :(

**Comment by frebib** [comment]
Oh ok, I wasn't aware that was required. I don't use Ubuntu myself so you're going to have to help me out here. If you want iodine bound to 53 you'll have to give up the local DNS resolver and connect directly to the DNS server (like everyone else).

Have a poke in `/etc/resolv.conf` and `/etc/systemd/network` and maybe `/etc/networking` and see if you can work out how the DNS is configured and try to remove the need for the local resolver.

Alternatively you can bind iodine to another port and use NAT at your router level to map the port back to 53- this one is a bit hacky but it might be easier

**Comment by nicopace** [comment]
I really don't care to which port iodine is bound to... could be any port if it simplifies the setup.
I guess what needs to be done is to tunnel the dns requests and the traffic both through the tunnel.
```
$ cat /etc/resolv.conf
nameserver 127.0.0.53
```

nothing in /etc/systemd/network or network/

```
$ cat /etc/network/interfaces
# interfaces(5) file used by ifup(8) and ifdown(8)
auto lo
iface lo inet loopback
```

What I thought could be done (although have not time now to explore it) is rerouting packets at the routing layer. 
Isn't adding a routing rule enough?

**Comment by frebib** [comment]
Ideally iodine should still be bound to port 53 on the external-facing IP. Is your setup subject to some kind of NAT/port forwarding?

My suggestion would be to bind iodine to `5353` or something similar and then forward the public-facing port 53 to your host on 5353. At some point in the future I shall have a play with Ubuntu and try to work out a sufficient workaround because this seems to be a recurring problem

**Comment by nicopace** [comment]
NAT/port forwarding is the most common scenario (airports, paywalls, firewalled network, etc).

**Comment by frebib** [comment]
Did you manage to get it running on a different port?

**Comment by nicopace** [comment]
Sorry @frebib couldn't get to this yet, just wanted to let you know about how it was in general for you to have more info about the usecases.
You can test it with a ubuntu VM in virtualbox for sure, but will try to do some time next week.

**Comment by JMyrng** [comment]
I got it working on Ubuntu 18. So here is what I have done:

1. disable resolved
`systemctl stop systemd-resolved` 
`systemctl disable systemd-resolved `

2. remove link and create a new resolv.conf
`rm /etc/resolv.conf`
`nano /etc/resolv.conf`

3. paste new nameservers in resolv.conf
`nameserver 1.1.1.1`
`nameserver 1.0.0.1`

4. save file and reboot the system

Can someone confirm that?

**Comment by frebib** [comment]
I'm not particularly familiar with how Ubuntu does DNS (aside from the fact that it is obviously broken). The only feedback I can provide is that rebooting is totally pointless. Just updating resolv.conf is enough.  You probably don't even need to stop/disable resolved.

Either way, deployment issues are not in any way an issue the container but instead an issue with the configuration of the host that the container is running on. There are multiple ways to work around the problem, depending on the situation. I'm happy to help anyone try to get it running on their system if they'd like
